### ISSUE TITLE
Rename to Iris Toolbox?

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#4]
The attacks in the _Eye_ toolbox are limited to iris artefacts. The overview also specifies that retina is outside the scope of the toolbox. Should this be changed to the _Iris_ toolbox?

**Comment by woodbe** [comment]
So originally this was called the iris toolbox, We changed it to eye because it was possible that other surface (or close to the surface) features could be used and have their own tests (or common ones with a different eye focus area). The point of saying retina is outside of the scope at this point was to make it clear the focus was not on things that required a more in-depth scan to see into the eye.

**Comment by woodbe** [comment]
Closing at this point based on consensus on 8/27 call.
