### ISSUE TITLE
Image Recommendations: Should vs Shall

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Eye-Toolbox#9]
In Overview, there is a section titled "Image Recommendations." As a recommendation, it is implied that the statements are not required, and one would expect _should_ normative statements. However, these recommendations seem to be necessary to create a proper artefact. For example:

> the Evaluator should attempt to acquire images where the iris diameter is at least 75 pixels

> When creating printed photos, the photo should be printed to have an equivalent of 1200 DPI.

The following statement has a _must_ statement (which should be changed to _shall_), and as such, is not a recommendation, but a normative requirement. 

> Note that when tests require the use of the contact lenses, the printed image of the iris must match the diameter of the contact lens for proper overlay.

I suggest changing the name of the section and making all statements within this section normative _shall_ statements.

**Comment by n-kai** [comment]
@gfiumara
I think that they should not be normative requirements.

The above specific information (e.g. 75 pixels) is a recommendation from one company based on their testing to just one iris recognition product (*1) and such specific condition may not be applicable to other products. So the evaluator shall look at research papers that fit to the TOE under evaluation before conducting pen testing.

That's the reason why @woodbe added a statement "**The evaluator shall consider relevant research papers to be authoritative over the generalized descriptions provided in a toolbox for improving the creation of artefacts**" to *2).  (@woodbe pls correct me if I am wrong but **generalized descriptions** can be replaced with **generalized or specific descriptions**)

*1) https://www.forbes.com/sites/thomasbrewster/2015/03/05/clone-putins-eyes-using-google-images/#3e90932b214a
*2) https://github.com/biometricITC/cPP-toolboxes/blob/master/toolbox.adoc#711-artefact-production

**Comment by gfiumara** [comment]
Okay, I understand. This subsection is serving to provide guidance one might glean from previous testing. Would it make sense to move this information to the _Penetration Testing and Attack Potential Rating Suggestions_ section of the individual attacks?

**Comment by n-kai** [comment]
Yes, I agree with @gfiumara

**Comment by woodbe** [comment]
So I don't know that I agree with that at this point (as I noted in the PR). I could agree with it being a suggestion, but I don't see the point of spinning it out into every individual test case unless we know there is something more specific that should cause a variation. I think we would be better served by providing more textual references in the overview and pointing out that the expectation is that all the tests performed by the lab meet some common set of requirements on the resolution. I think this is better handled globally instead of individually since the source would be the same, even if the usage may be different.

This isn't to say I disagree with the should to shall, just the move of the image requirements to the tests.

**Comment by gfiumara** [comment]
I did prepare a PR to the contrary, but I'm leaning your way @woodbe. More importantly, I've refreshed myself with iris imaging information from ISO/IEC 29794-6, which requires a minimum of 160 pixels. I've created a separate issue for this (#15).
